INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpy7v2pqdw
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpy7v2pqdw/_remote_module_non_scriptable.py
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/yanmy/enrich_release, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/yanmy/enrich_release, universal_newlines=False, shell=None, istream=None)
DEBUG:wandb.docker.auth:Trying paths: ['/home/yanmy/.docker/config.json', '/home/yanmy/.dockercfg']
DEBUG:wandb.docker.auth:No config file found
2023-12-24 18:40:38,850 - INFO - episode_0 Task: persons-2hop-k=2 f1-score: 0.8423794871794872, path: [0, 1, 2, 3, 4, 5, 6, 7, 8, 45, 46, 487, 488, 349, 350, 399, 400, 167, 168]
INFO:my_logger:episode_0 Task: persons-2hop-k=2 f1-score: 0.8423794871794872, path: [0, 1, 2, 3, 4, 5, 6, 7, 8, 45, 46, 487, 488, 349, 350, 399, 400, 167, 168]
DEBUG:filelock:Attempting to acquire lock 140176309828192 on /home/yanmy/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
DEBUG:filelock:Lock 140176309828192 acquired on /home/yanmy/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
DEBUG:filelock:Attempting to release lock 140176309828192 on /home/yanmy/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
DEBUG:filelock:Lock 140176309828192 released on /home/yanmy/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
DEBUG:filelock:Attempting to acquire lock 140176309828192 on /home/yanmy/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
DEBUG:filelock:Lock 140176309828192 acquired on /home/yanmy/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
DEBUG:filelock:Attempting to release lock 140176309828192 on /home/yanmy/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
DEBUG:filelock:Lock 140176309828192 released on /home/yanmy/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
